export const SET_SEARCHED_POSTS = "SET_SEARCHED_POSTS";
export const GET_SEARCHED_POSTS = "GET_SEARCHED_POSTS";
export const SET_NEXT_SEARCH_PAGE = "SET_NEXT_SEARCH_PAGE";
export const SET_SEARCH_MORE_DATA = "SET_SEARCH_MORE_DATA";
export const SET_MORE_SEARCHED_POSTS = "SET_MORE_SEARCHED_POSTS";
